app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

dt_content/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views.console import *
from .views.examples import *
from .views.utils import *

app_name = "dt-content"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "toggle-preview-mode",
        TogglePreviewModeView.as_view(),
        name="toggle-preview-mode",
    ),
    path("menus/", MenuListView.as_view(), name="menu-list"),
    path("menus/create/", MenuCreateView.as_view(), name="menu-create"),
    path("menus/update/<slug:slug>/", MenuUpdateView.as_view(), name="menu-update"),
    path("submenus/create/", SubmenuCreateView.as_view(), name="submenu-create"),
    path(
        "submenus/update/<slug:slug>/",
        SubmenuUpdateView.as_view(),
        name="submenu-update",
    ),
    path("menus/delete/<slug:slug>/", MenuDeleteView.as_view(), name="menu-delete"),
    path(
        "content-sections/",
        ContentSectionListView.as_view(),
        name="content-section-list",
    ),
    path(
        "content-sections/update/<slug:slug>/",
        ContentSectionUpdateView.as_view(),
        name="content-section-update",
    ),
    path(
        "content-section/delete/<slug:slug>/",
        ContentSectionDeleteView.as_view(),
        name="content-section-delete",
    ),
    path("content-blocks/", ContentBlockListView.as_view(), name="content-block-list"),
    path(
        "content-block/delete/<slug:slug>/",
        ContentBlockDeleteView.as_view(),
        name="content-block-delete",
    ),
    path("blurbs/", BlurbListView.as_view(), name="blurb-list"),
    path("blurbs/update/<slug:slug>/", BlurbUpdateView.as_view(), name="blurb-update"),
    path("image-blurbs/", ImageBlurbListView.as_view(), name="image-blurb-list"),
    path(
        "image-blurbs/update/<slug:slug>/",
        ImageBlurbUpdateView.as_view(),
        name="image-blurb-update",
    ),
    path(
        "rich-text-blocks/update/<slug:slug>/",
        RichTextBlockUpdateView.as_view(),
        name="rich-text-block-update",
    ),
    path(
        "rich-text-blocks/create/",
        RichTextBlockCreateView.as_view(),
        name="rich-text-block-create",
    ),
    path("example/block/", ExampleStaticBlockView.as_view(), name="example-block"),
    path(
        "example/section/", ExampleStaticSectionView.as_view(), name="example-section"
    ),
    path("example/blurb/", ExampleBlurbView.as_view(), name="example-blurb"),
    path(
        "example/image-blurb/",
        ExampleImageBlurbView.as_view(),
        name="example-image-blurb",
    ),
    path(
        "example/site_test/index/",
        ExampleSiteIndexView.as_view(),
        name="example-site-index",
    ),
    path(
        "example/site_test/<path:menu_path>/",
        ExampleSitePageView.as_view(),
        name="example-site-page",
    ),
    path(
        "example/site_test/",
        ExampleSitePageView.as_view(),
        name="example-site-page-base",
    ),
]

dt_content/views/console.py
import json

from django.core.exceptions import SuspiciousOperation
from django.shortcuts import redirect
from django.views.generic import *
from django.http import HttpResponseRedirect

from ..forms import *
from ..mixins import StaffMemberRequiredMixin
from ..models import *


class IndexView(StaffMemberRequiredMixin, TemplateView):
    template_name = "dt_content/console/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["static_section_count"] = ContentSection.static_objects.count()
        context["static_block_count"] = ContentBlock.static_objects.count()
        context["blurb_count"] = Blurb.objects.count()
        context["image_blurb_count"] = ImageBlurb.objects.count()
        return context


class MenuListView(StaffMemberRequiredMixin, ListView):
    queryset = Menu.objects.filter(parent=None)
    context_object_name = "menu_list"
    template_name = "dt_content/console/menu_list.html"


class MenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = MenuForm
    template_name = "dt_content/console/menu_create.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.object.id]) + "?success=true"
        )


class MenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = MenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if self.object.parent:  # if child menu, redirect to submenu update
            return redirect("dt-content:submenu-update", self.object.id)
        return response


class SubmenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = SubmenuForm
    template_name = "dt_content/console/submenu_create.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        parent = request.GET.get("parent", None)
        if not parent:
            raise SuspiciousOperation
        try:
            self.parent = Menu.objects.get(id=parent)
        except Menu.DoesNotExist as e:
            raise SuspiciousOperation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["parent"] = self.parent
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["parent"] = self.parent.id
        return initial

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.parent.id]) + "?success=true"
        )


class SubmenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = SubmenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/submenu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if not self.object.parent:  # if parent menu, redirect to menu update
            return redirect("dt-content:menu-update", self.object.id)
        return response


class MenuDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = Menu.objects
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentSectionListView(StaffMemberRequiredMixin, ListView):
    # Only lists static sections
    queryset = ContentSection.static_objects
    context_object_name = "content_section_list"
    template_name = "dt_content/console/content_section_list.html"


class ContentSectionUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ContentSection
    fields = []
    slug_field = "id"
    context_object_name = "section"
    template_name = "dt_content/console/content_section_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:content-section-list")
        return url + "?success=true"


class ContentSectionDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentSection.objects
    slug_field = "id"
    context_object_name = "content_section"
    template_name = "dt_content/console/content_section_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockListView(StaffMemberRequiredMixin, ListView):
    queryset = ContentBlock.objects.select_subclasses().filter(section=None)
    context_object_name = "content_block_list"
    template_name = "dt_content/console/content_block_list.html"


class ContentBlockDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentBlock.objects.select_subclasses()
    slug_field = "id"
    context_object_name = "content_block"
    template_name = "dt_content/console/content_block_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockUpdateView(StaffMemberRequiredMixin, UpdateView):  # Abstract class
    context_object_name = "object"  # can't use "block" due to collision
    slug_field = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list_url"] = self.object.console_list_url
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.object.console_list_url
        return url + "?success=true"


class ContentBlockCreateView(StaffMemberRequiredMixin, CreateView):
    # Functionality limitied to creating blocks associated with sections
    # Static content blocks are not supported

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        section = self.request.GET.get("section", None)
        if not section:
            raise SuspiciousOperation("Missing GET parameter: `section`")
        try:
            self.section = ContentSection.objects.get(id=section)
        except ContentSection.DoesNotExist as e:
            raise SuspiciousOperation("Could not find section {}".format(section))

    def get_initial(self):
        initial = super().get_initial()
        initial["section"] = self.section.id
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = self.section
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url

        return self.object.console_list_url


class BlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = Blurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "blurb_list"
    template_name = "dt_content/console/blurb_list.html"


class BlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Blurb
    form_class = BlurbForm
    slug_field = "id"
    context_object_name = "blurb"
    template_name = "dt_content/console/blurb_update.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)

        # Update last known location (only when it has been updated)
        next_url = self.request.GET.get("next", None)
        if next_url:
            self.object.last_known_location = next_url
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:blurb-list")
        return url + "?success=true"


class ImageBlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = ImageBlurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "image_blurb_list"
    template_name = "dt_content/console/image_blurb_list.html"


class ImageBlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ImageBlurb
    form_class = ImageBlurbForm
    slug_field = "id"
    context_object_name = "image_blurb"
    template_name = "dt_content/console/image_blurb_update.html"

dt_content/views/core.py
import logging
from typing import Tuple

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import ContextMixin, TemplateView

from ..menu import get_nav_menu_list
from ..mixins import PreviewModeMixin
from ..models import *


class PageContextMixin(PreviewModeMixin, ContextMixin):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

    menu_base_url = "/"
    menu_path_kwarg = "menu_path"

    def get_menu_base_url(self):
        return str(self.menu_base_url)  # may be lazy

    def get_current_menu(self, request):
        menu_path = self.kwargs.get(self.menu_path_kwarg)
        if not menu_path:
            return None

        slugs = menu_path.split("/")

        if len(slugs) not in [1, 2]:
            logging.warning("Invalid menu_path {}".format(menu_path))

        parent_slug = slugs[0]
        parent = get_object_or_404(Menu, url_slug=parent_slug, parent=None)

        if len(slugs) == 2:
            child_slug = slugs[1]
            child = get_object_or_404(Menu, url_slug=child_slug, parent=parent)
            return child

        return parent

    def get_nav_menu_list(self):
        return get_nav_menu_list(
            self.get_menu_base_url(), self.request.path, self.get_preview_mode()
        )

    def get_page_context_data(self, **kwargs):
        page_context = dict()

        current_menu = self.get_current_menu(self.request)
        nav_menu_list = self.get_nav_menu_list()

        nav_menu = None
        if current_menu:
            if current_menu.parent:
                parent_menu = current_menu.parent
                child_menu = current_menu
            else:
                parent_menu = current_menu
                child_menu = None

            # Search parent
            for menu in nav_menu_list:
                if menu["id"] == parent_menu.id:
                    nav_menu = menu
                    break
            else:
                logging.warning("Could not find current parent menu in menu_list")

            # Search child if exists
            if child_menu:
                for menu in nav_menu["children"]:
                    if menu["id"] == child_menu.id:
                        nav_menu = menu
                        break
                else:
                    logging.warning("Could not find current child menu in menu_list")
            page_context["content_section"] = current_menu.get_content_section()
            page_context["nav_menu"] = nav_menu

        page_context["nav_menu_list"] = nav_menu_list
        page_context["dt_content_preview_mode"] = self.get_preview_mode()

        return page_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_page_context_data())
        return context


PageMixin = PageContextMixin  # deprecated


class PageView(PageContextMixin, TemplateView):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

dt_content/templates/dt_content/content/blurb.html
{# Context Variables #}
{# blurb: Blurb #}

<span id="{{ blurb.html_id }}"></span>
{% if request.user.is_superuser and not dt_content_preview_mode %}
{% if blurb.plain_text %}
<!-- PLAIN TEXT BLURB ADMIN -->
<a href=" {% url 'dt-content:blurb-update' blurb.id %}?location={{ request.path }}&next={{ request.path }}"
  class="dt-content-blurb-inline-update-link">
  {% if blurb.content %}
  <i class="fas fa-edit"></i>
  {{ blurb.content|linebreaksbr }}
  {% else %}
  <i class="fas fa-edit"></i>
  Enter initial content
  {% endif %}
</a>
{% else %}
<!-- RICH BLURB ADMIN -->
<div class="d-flex">
  <div class="w-100">
    {% if blurb.content %}
    {{ blurb.content|safe }}
    <a href="{% url 'dt-content:blurb-update' blurb.id %}?location={{ request.path }}&next={{ request.path }}"
      class="dt-content-blurb-update-link">
      <i class="fas fa-edit"></i>
      Edit content
    </a>
    {% else %}
    <a href="{% url 'dt-content:blurb-update' blurb.id %}?location={{ request.path }}&next={{ request.path }}"
      class="dt-content-blurb-update-link">
      <i class="fas fa-edit"></i>
      Enter initial content</strong>
    </a>
    {% endif %}
  </div>
</div>
{% endif %}
{% else %}
{% if blurb.content %}
{% if blurb.plain_text %}
<!-- PLAIN TEXT BLURB -->
{{ blurb.content|linebreaksbr }}
{% else %}
<!-- RICH BLURB -->
<div class="d-flex">
  <div class="w-100">
    {{ blurb.content|safe }}
  </div>
</div>
{% endif %}
{% else %}
-
{% endif %}
{% endif %}

dt_content/templates/dt_content/content/content_block.html
{# Context variables #}
{# content_block: T extends ContentBlock #}
{% if request.user.is_staff and not dt_content_preview_mode %}
<div class="d-flex flex-col">
  <div class="flex-grow-1">
    <div class="dt-content-block-wrapper">
      <div class="dt-content-block-header">
        <div>
          <i class="fas fa-cog mr-2"></i>
          {{ content_block.block_type }}
        </div>
        <a class="btn btn-light btn-sm ml-3 mr-2" href="{{ content_block.update_url }}?next={{ request.path }}">
          <i class="fas fa-edit"></i>
          Edit
        </a>
        <a class="btn btn-light btn-sm mr-2"
          href="{% url 'dt-content:content-block-delete' content_block.id %}?next={{ request.path }}">
          <i class="fas fa-trash"></i>
          Delete
        </a>
      </div>
      {% include content_block.child_template_name %}
    </div>
  </div>
</div>
{% else %}
{% include content_block.child_template_name %}
{% endif %}

dt_content/templates/dt_content/content/content_section.html
{# Context variables #}
{# content_section: ContentSection #}

{% if request.user.is_staff and not dt_content_preview_mode %}
{# ADMIN VIEW #}
<div class="py-4">

  <div class="dt-content-section-header">
    <div class="mr-2 mb-3">
      <i class="fas fa-cog mr-2"></i>
      Content Section: {{ content_section.key }} {{ content_section.blocks.count }}
      Block(s)
    </div>
    {% if content_section.key %} {# Static section #}
    <a href="{% url 'dt-content:content-section-update' content_section.id %}?next={{ request.path }}"
      class="btn btn-light mr-2 mb-3">
      <i class="fas fa-bars"></i>
      Manage
    </a>
    {% else %} {# Non-static section: update menu instead of section #}
    <a href="{{ content_section.menu.update_url }}?next={{ request.path }}" class="btn btn-light mr-2 mb-3">
      <i class="fas fa-bars"></i>
      Manage
    </a>
    {% endif %}
    <button type="button" class="btn btn-light mb-3" data-toggle="modal" data-target="#add-block-modal">
      <i class="fas fa-plus"></i>
      Add Block
    </button>
  </div>
  <div>
    {% for content_block in content_section.blocks.all %}
    {% include content_block.template_name %}
    {% endfor %}
  </div>
  {% with modal_id='add-block-modal' %}
  {% include 'dt_content/snippets/add_block_modal.html' %}
  {% endwith %}
</div>
{% else %}
{# NORMAL USER VIEW #}
{% with content_section.blocks.all as blocks %}
<div>
  {% for content_block in blocks %}
  {% include content_block.template_name %}
  {% endfor %}
  {% if not blocks %}
  <div class="container">
    <div class="dt-content-empty-wrapper">
      <i class="fas fa-sticky-note dt-content-empty-icon"></i>
      <div class="dt-content-empty-label">This section is empty.</div>
    </div>
  </div>
  {% endif %}
</div>
{% endwith %}
{% endif %}

dt_content/templates/dt_content/content/image_blurb_update_link.html
{# Context Variables #}
{# image_blurb: Blurb #}
{# image_blurb_update_message?: string #}

<span id="{{ image_blurb.html_id }}"></span>
{% if request.user.is_superuser and not dt_content_preview_mode %}
<a href="{{ image_blurb.update_url }}?location={{ request.path }}&next={{ request.path }}"
  class="dt-content-image-blurb-update-link btn btn-outline-primary">
  <i class="fas fa-edit"></i>
  {% if image_blurb_update_message %}
  {{ image_blurb_update_message }}
  {% else %}
  Update Image
  {% endif %}
</a>
{% endif %}

dt_content/templates/dt_content/content/rich_text_block.html
{# Context varables #}
{# content_block: RichTextBlock #}
<div class="container py-5">
  <div class="row">
    <div class="col-12 col-md-11 col-lg-10 col-xl-9">
      {{ content_block.content|safe }}
    </div>
  </div>
</div>