app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

dt_content/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views.console import *
from .views.examples import *
from .views.utils import *

app_name = "dt-content"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "toggle-preview-mode",
        TogglePreviewModeView.as_view(),
        name="toggle-preview-mode",
    ),
    path("menus/", MenuListView.as_view(), name="menu-list"),
    path("menus/create/", MenuCreateView.as_view(), name="menu-create"),
    path("menus/update/<slug:slug>/", MenuUpdateView.as_view(), name="menu-update"),
    path("submenus/create/", SubmenuCreateView.as_view(), name="submenu-create"),
    path(
        "submenus/update/<slug:slug>/",
        SubmenuUpdateView.as_view(),
        name="submenu-update",
    ),
    path("menus/delete/<slug:slug>/", MenuDeleteView.as_view(), name="menu-delete"),
    path(
        "content-sections/",
        ContentSectionListView.as_view(),
        name="content-section-list",
    ),
    path(
        "content-sections/update/<slug:slug>/",
        ContentSectionUpdateView.as_view(),
        name="content-section-update",
    ),
    path(
        "content-section/delete/<slug:slug>/",
        ContentSectionDeleteView.as_view(),
        name="content-section-delete",
    ),
    path("content-blocks/", ContentBlockListView.as_view(), name="content-block-list"),
    path(
        "content-block/delete/<slug:slug>/",
        ContentBlockDeleteView.as_view(),
        name="content-block-delete",
    ),
    path("blurbs/", BlurbListView.as_view(), name="blurb-list"),
    path("blurbs/update/<slug:slug>/", BlurbUpdateView.as_view(), name="blurb-update"),
    path("image-blurbs/", ImageBlurbListView.as_view(), name="image-blurb-list"),
    path(
        "image-blurbs/update/<slug:slug>/",
        ImageBlurbUpdateView.as_view(),
        name="image-blurb-update",
    ),
    path(
        "rich-text-blocks/update/<slug:slug>/",
        RichTextBlockUpdateView.as_view(),
        name="rich-text-block-update",
    ),
    path(
        "rich-text-blocks/create/",
        RichTextBlockCreateView.as_view(),
        name="rich-text-block-create",
    ),
    path("example/block/", ExampleStaticBlockView.as_view(), name="example-block"),
    path(
        "example/section/", ExampleStaticSectionView.as_view(), name="example-section"
    ),
    path("example/blurb/", ExampleBlurbView.as_view(), name="example-blurb"),
    path(
        "example/image-blurb/",
        ExampleImageBlurbView.as_view(),
        name="example-image-blurb",
    ),
    path(
        "example/site_test/index/",
        ExampleSiteIndexView.as_view(),
        name="example-site-index",
    ),
    path(
        "example/site_test/<path:menu_path>/",
        ExampleSitePageView.as_view(),
        name="example-site-page",
    ),
    path(
        "example/site_test/",
        ExampleSitePageView.as_view(),
        name="example-site-page-base",
    ),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

dt_content/views/console.py
import json

from django.core.exceptions import SuspiciousOperation
from django.shortcuts import redirect
from django.views.generic import *
from django.http import HttpResponseRedirect

from ..forms import *
from ..mixins import StaffMemberRequiredMixin
from ..models import *


class IndexView(StaffMemberRequiredMixin, TemplateView):
    template_name = "dt_content/console/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["static_section_count"] = ContentSection.static_objects.count()
        context["static_block_count"] = ContentBlock.static_objects.count()
        context["blurb_count"] = Blurb.objects.count()
        context["image_blurb_count"] = ImageBlurb.objects.count()
        return context


class MenuListView(StaffMemberRequiredMixin, ListView):
    queryset = Menu.objects.filter(parent=None)
    context_object_name = "menu_list"
    template_name = "dt_content/console/menu_list.html"


class MenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = MenuForm
    template_name = "dt_content/console/menu_create.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.object.id]) + "?success=true"
        )


class MenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = MenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if self.object.parent:  # if child menu, redirect to submenu update
            return redirect("dt-content:submenu-update", self.object.id)
        return response


class SubmenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = SubmenuForm
    template_name = "dt_content/console/submenu_create.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        parent = request.GET.get("parent", None)
        if not parent:
            raise SuspiciousOperation
        try:
            self.parent = Menu.objects.get(id=parent)
        except Menu.DoesNotExist as e:
            raise SuspiciousOperation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["parent"] = self.parent
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["parent"] = self.parent.id
        return initial

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.parent.id]) + "?success=true"
        )


class SubmenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = SubmenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/submenu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if not self.object.parent:  # if parent menu, redirect to menu update
            return redirect("dt-content:menu-update", self.object.id)
        return response


class MenuDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = Menu.objects
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentSectionListView(StaffMemberRequiredMixin, ListView):
    # Only lists static sections
    queryset = ContentSection.static_objects
    context_object_name = "content_section_list"
    template_name = "dt_content/console/content_section_list.html"


class ContentSectionUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ContentSection
    fields = []
    slug_field = "id"
    context_object_name = "section"
    template_name = "dt_content/console/content_section_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:content-section-list")
        return url + "?success=true"


class ContentSectionDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentSection.objects
    slug_field = "id"
    context_object_name = "content_section"
    template_name = "dt_content/console/content_section_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockListView(StaffMemberRequiredMixin, ListView):
    queryset = ContentBlock.objects.select_subclasses().filter(section=None)
    context_object_name = "content_block_list"
    template_name = "dt_content/console/content_block_list.html"


class ContentBlockDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentBlock.objects.select_subclasses()
    slug_field = "id"
    context_object_name = "content_block"
    template_name = "dt_content/console/content_block_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockUpdateView(StaffMemberRequiredMixin, UpdateView):  # Abstract class
    context_object_name = "object"  # can't use "block" due to collision
    slug_field = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list_url"] = self.object.console_list_url
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.object.console_list_url
        return url + "?success=true"


class ContentBlockCreateView(StaffMemberRequiredMixin, CreateView):
    # Functionality limitied to creating blocks associated with sections
    # Static content blocks are not supported

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        section = self.request.GET.get("section", None)
        if not section:
            raise SuspiciousOperation("Missing GET parameter: `section`")
        try:
            self.section = ContentSection.objects.get(id=section)
        except ContentSection.DoesNotExist as e:
            raise SuspiciousOperation("Could not find section {}".format(section))

    def get_initial(self):
        initial = super().get_initial()
        initial["section"] = self.section.id
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = self.section
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url

        return self.object.console_list_url


class BlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = Blurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "blurb_list"
    template_name = "dt_content/console/blurb_list.html"


class BlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Blurb
    form_class = BlurbForm
    slug_field = "id"
    context_object_name = "blurb"
    template_name = "dt_content/console/blurb_update.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)

        # Update last known location (only when it has been updated)
        next_url = self.request.GET.get("next", None)
        if next_url:
            self.object.last_known_location = next_url
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:blurb-list")
        return url + "?success=true"


class ImageBlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = ImageBlurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "image_blurb_list"
    template_name = "dt_content/console/image_blurb_list.html"


class ImageBlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ImageBlurb
    form_class = ImageBlurbForm
    slug_field = "id"
    context_object_name = "image_blurb"
    template_name = "dt_content/console/image_blurb_update.html"

dt_content/views/core.py
import logging
from typing import Tuple

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import ContextMixin, TemplateView

from ..menu import get_nav_menu_list
from ..mixins import PreviewModeMixin
from ..models import *


class PageContextMixin(PreviewModeMixin, ContextMixin):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

    menu_base_url = "/"
    menu_path_kwarg = "menu_path"

    def get_menu_base_url(self):
        return str(self.menu_base_url)  # may be lazy

    def get_current_menu(self, request):
        menu_path = self.kwargs.get(self.menu_path_kwarg)
        if not menu_path:
            return None

        slugs = menu_path.split("/")

        if len(slugs) not in [1, 2]:
            logging.warning("Invalid menu_path {}".format(menu_path))

        parent_slug = slugs[0]
        parent = get_object_or_404(Menu, url_slug=parent_slug, parent=None)

        if len(slugs) == 2:
            child_slug = slugs[1]
            child = get_object_or_404(Menu, url_slug=child_slug, parent=parent)
            return child

        return parent

    def get_nav_menu_list(self):
        return get_nav_menu_list(
            self.get_menu_base_url(), self.request.path, self.get_preview_mode()
        )

    def get_page_context_data(self, **kwargs):
        page_context = dict()

        current_menu = self.get_current_menu(self.request)
        nav_menu_list = self.get_nav_menu_list()

        nav_menu = None
        if current_menu:
            if current_menu.parent:
                parent_menu = current_menu.parent
                child_menu = current_menu
            else:
                parent_menu = current_menu
                child_menu = None

            # Search parent
            for menu in nav_menu_list:
                if menu["id"] == parent_menu.id:
                    nav_menu = menu
                    break
            else:
                logging.warning("Could not find current parent menu in menu_list")

            # Search child if exists
            if child_menu:
                for menu in nav_menu["children"]:
                    if menu["id"] == child_menu.id:
                        nav_menu = menu
                        break
                else:
                    logging.warning("Could not find current child menu in menu_list")
            page_context["content_section"] = current_menu.get_content_section()
            page_context["nav_menu"] = nav_menu

        page_context["nav_menu_list"] = nav_menu_list
        page_context["dt_content_preview_mode"] = self.get_preview_mode()

        return page_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_page_context_data())
        return context


PageMixin = PageContextMixin  # deprecated


class PageView(PageContextMixin, TemplateView):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

dt_content/templates/dt_content/console/blurb_list.html
{% extends 'dt_content/console/base.html' %}

{% block body %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dt-content:index' %}">Console</a></li>
      <li class="breadcrumb-item active" aria-current="page">All Blurbs</li>
    </ol>
  </nav>
</div>

<div class="container py-4">
  <div class="d-flex align-items-center mb-4">
    <h3 class="m-0 mr-3">All Blurbs</h3>
  </div>

  {% if request.GET.success == 'true' %}
  <div class="alert alert-success">Update successful</div>
  {% endif %}
  <div class="row">
    {% for blurb in blurb_list %}
    <div class="col-12">
      <div class="card d-flex flex-row align-items-center mb-3 ">
        <a href="{% url 'dt-content:blurb-update' blurb.id %}" class="text-decoration-none">
          <h4 class="m-0 mr-3">{{ blurb.display_name }}</h4>
        </a>
        {% if blurb.last_known_location %}
        <p class="m-0 mr-3">{{ blurb.last_known_location }} </p>
        <a href="{{ blurb.href }}" class="ml-auto btn btn-outline-primary">
          View on Page
        </a>
        {% endif %}
      </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

dt_content/templates/dt_content/console/blurb_update.html
{% extends 'dt_content/console/base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% include 'dt_content/snippets/breadcrumbs/blurb.html' %}
    </ol>
  </nav>
</div>

<div class="container py-4">
  <div class="mb-5">
    <div class="header-label">
      Blurb
    </div>
    <h2 class="mt-0">{{ blurb.display_name }}</h2>
    {% if blurb.last_known_location%}
    <div class="header-label">
      Last Known Location
    </div>
    <a href="{{ blurb.href }}" class="text-decoration-none">
      <h3 class="text-primary">
        {{ blurb.last_known_location }}
      </h3>
    </a>
    {% endif %}
  </div>

  <div class="mb-4">
    {% if request.GET.success == 'true' %}
    <div class="alert alert-success">Update successful</div>
    {% endif %}
    <form method="post">
      {% csrf_token %}
      {{ form.media }}
      {% bootstrap_form form %}
      <button class="btn btn-primary">Save</button>
    </form>
  </div>
  {% endblock %}

dt_content/templates/dt_content/console/index.html
{% extends 'dt_content/console/base.html' %}

{% block body %}
<div class="container py-4">
  <h3>Console</h3>
  <div class="row">
    <!-- MANAGEMENT -->
    <div class="col-12 col-md-5">
      <a href="{% url 'dt-content:menu-list' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Manage Site
      </a>
      <a href="{% url 'dt-content:content-section-list' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Static Sections: {{ static_section_count }}
      </a>
      <a href="{% url 'dt-content:content-block-list' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Static Blocks: {{ static_block_count }}
      </a>
      <a href="{% url 'dt-content:blurb-list' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Blurbs: {{ blurb_count }}
      </a>
      <a href="{% url 'dt-content:image-blurb-list' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Image Blurbs: {{ image_blurb_count }}
      </a>
    </div>

    <!-- EXAMPLES -->
    <div class="col-12 col-md-5">
      <a href="{% url 'dt-content:example-site-index' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Site Example
      </a>
      <a href="{% url 'dt-content:example-section' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Static Section Example
      </a>
      <a href="{% url 'dt-content:example-block' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Static Block Example
      </a>
      <a href="{% url 'dt-content:example-blurb' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Blurb Example
      </a>
      <a href="{% url 'dt-content:example-image-blurb' %}" class="btn btn-light btn-block btn-lg text-left mb-2 px-4">
        Image Blurb Example
      </a>
    </div>
  </div>
</div>
{% endblock %}

dt_content/templates/dt_content/console/menu_create.html
{% extends 'dt_content/console/base.html' %}
{% load bootstrap4 %}

{% block body %}

<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dt-content:index' %}">Console</a></li>
      <li class="breadcrumb-item"><a href="{% url 'dt-content:menu-list' %}">All Menus</a></li>
      <li class="breadcrumb-item active" aria-current="page">New Menu</li>
    </ol>
  </nav>
</div>

<div class="container py-4">
  <h3>New Menu</h3>
  <form method="post">
    {% csrf_token %}
    <div class="mb-4">
      {% include 'dt_content/snippets/menu_form_row.html' %}
    </div>
    <button class="btn btn-primary">Create Menu</button>
  </form>
</div>
{% endblock %}

dt_content/templates/dt_content/console/menu_list.html
{% extends 'dt_content/console/base.html' %}

{% block body %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'dt-content:index' %}">Console</a></li>
      <li class="breadcrumb-item active" aria-current="page">All Menus</li>
    </ol>
  </nav>
</div>

<div class="container py-4">
  <div class="d-flex align-items-center mb-4">
    <h3 class="m-0 mr-3">All Menus</h3>
    <a href="{% url 'dt-content:menu-create' %}" class="text-decoration-none d-block">
      <button class="btn btn-primary">Create Menu</button>
    </a>
  </div>

  {% if request.GET.success == 'true' %}
  <div class="alert alert-success">Update successful</div>
  {% endif %}
  <div class="row">
    {% for menu in menu_list %}
    <div class="col-12">
      <div class="card d-flex flex-row align-items-center mb-3 ">
        <a href="{% url 'dt-content:menu-update' menu.id %}" class="text-decoration-none">
          <h4 class="m-0 mr-3">{{ menu.title }}</h4>
        </a>
        <p class="m-0 mr-3"> /{{ menu.url_slug }} </p>
        <p class="m-0 mr-3"> {{ menu.children.count }} submenu(s)</p>
        <a href="{% url 'dt-content:menu-delete' menu.id %}" class="ml-auto btn btn-outline-danger">Delete</a>
      </div>
      </a>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

dt_content/templates/dt_content/console/menu_update.html
{% extends 'dt_content/console/base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% include 'dt_content/snippets/breadcrumbs/menu.html' %}
    </ol>
  </nav>
</div>

<div class="container py-4">
  {% if request.GET.success == 'true' %}
  <div class="alert alert-success">Update successful</div>
  {% endif %}

  <div class="mb-4">
    <div class="header-label">
      Menu
    </div>
    <h2 class="mt-0">{{ menu.title }}</h2>
  </div>
  <form action="{{ request.path }}" method="post" class="mb-5">
    {% csrf_token %}
    {% include "dt_content/snippets/menu_form_row.html" %}
    <a href="{% url 'dt-content:menu-delete' menu.id %}" class="btn btn-danger">Delete</a>
    <button class="btn btn-primary" type="submit">Update</button>
    <a href="{% url 'dt-content:example-site-page' menu.url_path %}" class="btn btn-primary">Preview</a>
  </form>

  <div class="mb-4">
    <h3>Submenus</h3>
    <div class="row">
      {% for submenu in menu.children.all %}
      <div class="col-12">
        <div class="card d-flex flex-row align-items-center mb-3">
          <a href="{% url 'dt-content:submenu-update' submenu.id %}" class="text-decoration-none">
            <h4 class="m-0 mr-2">{{ submenu.title }}</h4>
          </a>
          <p class="m-0"> {{ menu.url_slug }}/{{ submenu.url_slug }}</p>
          {% if submenu.disabled %}
          <p class="m-0 ml-auto text-">Disabled</p>
          {% endif %}
          <a href="{% url 'dt-content:menu-delete' submenu.id %}" class="ml-auto btn btn-outline-danger">Delete</a>
        </div>
      </div>
      {% endfor %}
      <div class="col-12">
        <a href="{% url 'dt-content:submenu-create' %}?parent={{ object.id }}" class="text-decoration-none d-block">
          <div class="card mb-3 text-center">
            <p class="m-0"><i class="fas fa-plus"></i> Add Submenu</p>
          </div>
        </a>
      </div>
    </div>
  </div>

  <div class="mb-4">
    <h3>Content Blocks</h3>
    <div class="row">
      {% with section=menu.get_content_section %}
      {% for block in section.blocks %}
      {% include 'dt_content/snippets/block_listing_column.html' %}
      {% endfor %}

      {% include 'dt_content/snippets/add_block_column.html' %}
      {% endwith %}
    </div>
  </div>
</div>
{% endblock %}

dt_content/templates/dt_content/console/submenu_update.html
{% extends 'dt_content/console/base.html' %}
{% load bootstrap4 %}

{% block body %}
<div class="container">
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      {% include 'dt_content/snippets/breadcrumbs/menu.html' %}
    </ol>
  </nav>
</div>

<div class="container py-4">
  {% if request.GET.success == 'true' %}
  <div class="alert alert-success">Update successful</div>
  {% endif %}

  <div class="mb-4 d-flex flex-col align-items-center">
    <a href="{{ parent.update_url }}" class="text-decoration-none">
      <div class="header-label">Menu</div>
      <h2 class="mt-0">{{ menu.parent.title }}</h2>
    </a>
    <i class="fas fa-caret-right mx-3"></i>
    <div>
      <div class="header-label">Submenu</div>
      <h2 class="mt-0">{{ menu.title }}</h2>
    </div>
  </div>

  <form action="{{ request.path }}" method="post" class="mb-5">
    {% csrf_token %}
    {% include "dt_content/snippets/menu_form_row.html" %}
    <a href="{% url 'dt-content:menu-delete' menu.id %}" class="btn btn-danger">Delete</a>
    <button class="btn btn-primary" type="submit">Update</button>
    <a href="{% url 'dt-content:example-site-page' menu.url_path %}" class="btn btn-primary">Preview</a>
  </form>

  <div class="mb-4">
    <h3>Content Blocks</h3>
    <div class="row">
      {% with section=menu.get_content_section %}
      {% for block in section.blocks %}
      {% include 'dt_content/snippets/block_listing_column.html' %}
      {% endfor %}

      {% include 'dt_content/snippets/add_block_column.html' %}
      {% endwith %}
    </div>
  </div>
</div>
{% endblock %}