app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("work", WorkView.as_view(), name="work"),
    path("blog", BlogView.as_view(), name="blog"),
]

dt_content/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views.console import *
from .views.examples import *
from .views.utils import *

app_name = "dt-content"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path(
        "toggle-preview-mode",
        TogglePreviewModeView.as_view(),
        name="toggle-preview-mode",
    ),
    path("menus/", MenuListView.as_view(), name="menu-list"),
    path("menus/create/", MenuCreateView.as_view(), name="menu-create"),
    path("menus/update/<slug:slug>/", MenuUpdateView.as_view(), name="menu-update"),
    path("submenus/create/", SubmenuCreateView.as_view(), name="submenu-create"),
    path(
        "submenus/update/<slug:slug>/",
        SubmenuUpdateView.as_view(),
        name="submenu-update",
    ),
    path("menus/delete/<slug:slug>/", MenuDeleteView.as_view(), name="menu-delete"),
    path(
        "content-sections/",
        ContentSectionListView.as_view(),
        name="content-section-list",
    ),
    path(
        "content-sections/update/<slug:slug>/",
        ContentSectionUpdateView.as_view(),
        name="content-section-update",
    ),
    path(
        "content-section/delete/<slug:slug>/",
        ContentSectionDeleteView.as_view(),
        name="content-section-delete",
    ),
    path("content-blocks/", ContentBlockListView.as_view(), name="content-block-list"),
    path(
        "content-block/delete/<slug:slug>/",
        ContentBlockDeleteView.as_view(),
        name="content-block-delete",
    ),
    path("blurbs/", BlurbListView.as_view(), name="blurb-list"),
    path("blurbs/update/<slug:slug>/", BlurbUpdateView.as_view(), name="blurb-update"),
    path("image-blurbs/", ImageBlurbListView.as_view(), name="image-blurb-list"),
    path(
        "image-blurbs/update/<slug:slug>/",
        ImageBlurbUpdateView.as_view(),
        name="image-blurb-update",
    ),
    path(
        "rich-text-blocks/update/<slug:slug>/",
        RichTextBlockUpdateView.as_view(),
        name="rich-text-block-update",
    ),
    path(
        "rich-text-blocks/create/",
        RichTextBlockCreateView.as_view(),
        name="rich-text-block-create",
    ),
    path("example/block/", ExampleStaticBlockView.as_view(), name="example-block"),
    path(
        "example/section/", ExampleStaticSectionView.as_view(), name="example-section"
    ),
    path("example/blurb/", ExampleBlurbView.as_view(), name="example-blurb"),
    path(
        "example/image-blurb/",
        ExampleImageBlurbView.as_view(),
        name="example-image-blurb",
    ),
    path(
        "example/site_test/index/",
        ExampleSiteIndexView.as_view(),
        name="example-site-index",
    ),
    path(
        "example/site_test/<path:menu_path>/",
        ExampleSitePageView.as_view(),
        name="example-site-page",
    ),
    path(
        "example/site_test/",
        ExampleSitePageView.as_view(),
        name="example-site-page-base",
    ),
]

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render

dt_content/views/console.py
import json

from django.core.exceptions import SuspiciousOperation
from django.shortcuts import redirect
from django.views.generic import *
from django.http import HttpResponseRedirect

from ..forms import *
from ..mixins import StaffMemberRequiredMixin
from ..models import *


class IndexView(StaffMemberRequiredMixin, TemplateView):
    template_name = "dt_content/console/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["static_section_count"] = ContentSection.static_objects.count()
        context["static_block_count"] = ContentBlock.static_objects.count()
        context["blurb_count"] = Blurb.objects.count()
        context["image_blurb_count"] = ImageBlurb.objects.count()
        return context


class MenuListView(StaffMemberRequiredMixin, ListView):
    queryset = Menu.objects.filter(parent=None)
    context_object_name = "menu_list"
    template_name = "dt_content/console/menu_list.html"


class MenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = MenuForm
    template_name = "dt_content/console/menu_create.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.object.id]) + "?success=true"
        )


class MenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = MenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if self.object.parent:  # if child menu, redirect to submenu update
            return redirect("dt-content:submenu-update", self.object.id)
        return response


class SubmenuCreateView(StaffMemberRequiredMixin, CreateView):
    form_class = SubmenuForm
    template_name = "dt_content/console/submenu_create.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        parent = request.GET.get("parent", None)
        if not parent:
            raise SuspiciousOperation
        try:
            self.parent = Menu.objects.get(id=parent)
        except Menu.DoesNotExist as e:
            raise SuspiciousOperation

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["parent"] = self.parent
        return context

    def get_initial(self):
        initial = super().get_initial()
        initial["parent"] = self.parent.id
        return initial

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url
        return (
            reverse("dt-content:menu-update", args=[self.parent.id]) + "?success=true"
        )


class SubmenuUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Menu
    form_class = SubmenuForm
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/submenu_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.request.path
        return url + "?success=true"

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        if not self.object.parent:  # if parent menu, redirect to menu update
            return redirect("dt-content:menu-update", self.object.id)
        return response


class MenuDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = Menu.objects
    slug_field = "id"
    context_object_name = "menu"
    template_name = "dt_content/console/menu_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentSectionListView(StaffMemberRequiredMixin, ListView):
    # Only lists static sections
    queryset = ContentSection.static_objects
    context_object_name = "content_section_list"
    template_name = "dt_content/console/content_section_list.html"


class ContentSectionUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ContentSection
    fields = []
    slug_field = "id"
    context_object_name = "section"
    template_name = "dt_content/console/content_section_update.html"

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:content-section-list")
        return url + "?success=true"


class ContentSectionDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentSection.objects
    slug_field = "id"
    context_object_name = "content_section"
    template_name = "dt_content/console/content_section_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockListView(StaffMemberRequiredMixin, ListView):
    queryset = ContentBlock.objects.select_subclasses().filter(section=None)
    context_object_name = "content_block_list"
    template_name = "dt_content/console/content_block_list.html"


class ContentBlockDeleteView(StaffMemberRequiredMixin, DeleteView):
    queryset = ContentBlock.objects.select_subclasses()
    slug_field = "id"
    context_object_name = "content_block"
    template_name = "dt_content/console/content_block_delete.html"

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.next_url = self.request.GET.get("next", None)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next_url"] = self.next_url or self.object.console_list_url
        return context

    def get_success_url(self):
        return (self.next_url or self.object.console_list_url) + "?delete_success=True"


class ContentBlockUpdateView(StaffMemberRequiredMixin, UpdateView):  # Abstract class
    context_object_name = "object"  # can't use "block" due to collision
    slug_field = "id"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object_list_url"] = self.object.console_list_url
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or self.object.console_list_url
        return url + "?success=true"


class ContentBlockCreateView(StaffMemberRequiredMixin, CreateView):
    # Functionality limitied to creating blocks associated with sections
    # Static content blocks are not supported

    def setup(self, *args, **kwargs):
        super().setup(*args, **kwargs)
        section = self.request.GET.get("section", None)
        if not section:
            raise SuspiciousOperation("Missing GET parameter: `section`")
        try:
            self.section = ContentSection.objects.get(id=section)
        except ContentSection.DoesNotExist as e:
            raise SuspiciousOperation("Could not find section {}".format(section))

    def get_initial(self):
        initial = super().get_initial()
        initial["section"] = self.section.id
        return initial

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["section"] = self.section
        return context

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        if next_url:
            return next_url

        return self.object.console_list_url


class BlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = Blurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "blurb_list"
    template_name = "dt_content/console/blurb_list.html"


class BlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = Blurb
    form_class = BlurbForm
    slug_field = "id"
    context_object_name = "blurb"
    template_name = "dt_content/console/blurb_update.html"

    def form_valid(self, form):
        self.object = form.save(commit=False)

        # Update last known location (only when it has been updated)
        next_url = self.request.GET.get("next", None)
        if next_url:
            self.object.last_known_location = next_url
        self.object.save()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get("next", None)
        url = next_url or reverse("dt-content:blurb-list")
        return url + "?success=true"


class ImageBlurbListView(StaffMemberRequiredMixin, ListView):
    queryset = ImageBlurb.objects.order_by("last_known_location", "identifier")
    context_object_name = "image_blurb_list"
    template_name = "dt_content/console/image_blurb_list.html"


class ImageBlurbUpdateView(StaffMemberRequiredMixin, UpdateView):
    model = ImageBlurb
    form_class = ImageBlurbForm
    slug_field = "id"
    context_object_name = "image_blurb"
    template_name = "dt_content/console/image_blurb_update.html"

dt_content/views/core.py
import logging
from typing import Tuple

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import ContextMixin, TemplateView

from ..menu import get_nav_menu_list
from ..mixins import PreviewModeMixin
from ..models import *


class PageContextMixin(PreviewModeMixin, ContextMixin):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

    menu_base_url = "/"
    menu_path_kwarg = "menu_path"

    def get_menu_base_url(self):
        return str(self.menu_base_url)  # may be lazy

    def get_current_menu(self, request):
        menu_path = self.kwargs.get(self.menu_path_kwarg)
        if not menu_path:
            return None

        slugs = menu_path.split("/")

        if len(slugs) not in [1, 2]:
            logging.warning("Invalid menu_path {}".format(menu_path))

        parent_slug = slugs[0]
        parent = get_object_or_404(Menu, url_slug=parent_slug, parent=None)

        if len(slugs) == 2:
            child_slug = slugs[1]
            child = get_object_or_404(Menu, url_slug=child_slug, parent=parent)
            return child

        return parent

    def get_nav_menu_list(self):
        return get_nav_menu_list(
            self.get_menu_base_url(), self.request.path, self.get_preview_mode()
        )

    def get_page_context_data(self, **kwargs):
        page_context = dict()

        current_menu = self.get_current_menu(self.request)
        nav_menu_list = self.get_nav_menu_list()

        nav_menu = None
        if current_menu:
            if current_menu.parent:
                parent_menu = current_menu.parent
                child_menu = current_menu
            else:
                parent_menu = current_menu
                child_menu = None

            # Search parent
            for menu in nav_menu_list:
                if menu["id"] == parent_menu.id:
                    nav_menu = menu
                    break
            else:
                logging.warning("Could not find current parent menu in menu_list")

            # Search child if exists
            if child_menu:
                for menu in nav_menu["children"]:
                    if menu["id"] == child_menu.id:
                        nav_menu = menu
                        break
                else:
                    logging.warning("Could not find current child menu in menu_list")
            page_context["content_section"] = current_menu.get_content_section()
            page_context["nav_menu"] = nav_menu

        page_context["nav_menu_list"] = nav_menu_list
        page_context["dt_content_preview_mode"] = self.get_preview_mode()

        return page_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_page_context_data())
        return context


PageMixin = PageContextMixin  # deprecated


class PageView(PageContextMixin, TemplateView):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

dt_content/templates/dt_content/example/site/base.html
{% load static %}

<!-- Uses boilerplate from http://html5boilerplate.com -->
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js">
<!--<![endif]-->

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css" />

  <link rel="stylesheet" href="{% static 'dt_content/css/base.css' %}">
  <link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">

  {% block head %}
  {% endblock head%}

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous">
    </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
</head>

<body>
  <!--[if lt IE 7]>
      <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
  {% block body %}
  {% endblock body %}

  {% block body_script %}
  {% endblock body_script %}
</body>

</html>

dt_content/templates/dt_content/example/site/footer.html
<div class="footer">
  <div class="container">
    <div class="py-5">
      <span class="footer-title">Dt Content Footer</span>
    </div>
    <div class="py-2">
      <span class="footer-copyright">Dt Content © {% now "Y" %} Namgyu Ho, All Rights Reserved.</span>
    </div>
  </div>
</div>

dt_content/templates/dt_content/example/site/index.html
{% extends 'dt_content/example/site/base.html' %}
{% load static %}
{% load dt_content %}

{% block head %}
<title>django-template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/example/styles.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/navbar.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/header.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/footer.css' %}">
{% endblock head%}

{% block body %}

{% include 'dt_content/example/site/navbar.html' %}

<div class="header header-lg">
  <div class="header-background" style="background-image: url('{% static 'dt_content/img/example/background.jpg' %}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container h-100 d-flex flex-column justify-content-center">
      <div class="hero-title">dt-content Example Site</div>
    </div>
  </div>
</div>

<div class="content">
  <div class="container py-5">
    <div class="mb-5">
      <h1>dt-content Example Site</h1>
      <p>
        This is an auto generated example site.
      </p>
    </div>

    <div class="mb-5">
      <h2>Actions</h2>
      <div class="row">
        <div class="col-12 col-sm-6">
          <a href="{% url 'dt-content:index' %}" class="btn btn-light btn-block">
            Return To Console
          </a>
          <a href="{% url 'dt-content:menu-list' %}" class="btn btn-light btn-block">
            Manage Site
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

{% include 'dt_content/example/site/footer.html' %}

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

dt_content/templates/dt_content/example/site/navbar.html
{% load static %}

<nav class="fixed-top">
  <div class="navbar-top">
    <div class="container">
      <div class="d-flex justify-content-end">
        {% if request.user.is_authenticated %}
        {% if request.user.is_staff %}
        {% if dt_content_preview_mode %}
        <a class="btn navbar-top-button"
          href="{% url 'dt-content:toggle-preview-mode' %}?mode=false&next={{ request.path }}">
          EXIT PREVIEW MODE
        </a>
        {% else %}
        <a class="btn navbar-top-button"
          href="{% url 'dt-content:toggle-preview-mode' %}?mode=true&next={{ request.path }}">
          ENTER PREVIEW MODE
        </a>
        {% endif %}
        {% endif %}
        <a class="btn navbar-top-button" href="{% url 'account_logout' %}">SIGN OUT</a>
        {% else %}
        <a class="btn navbar-top-button" href="{% url 'account_login' %}">LOG IN</a>
        <a class="btn navbar-top-button" href="{% url 'account_signup' %}">SIGN UP</a>
        {% endif %}
      </div>
    </div>
  </div>
  <div class="navbar-middle navbar navbar-expand-lg navbar-dark">
    <div class="container">
      <a class="navbar-brand nav-title" href="{% url 'core:index' %}">
        Django Template
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% for menu in nav_menu_list %}
          {% if not menu.disabled %}
          <li class="nav-item">
            <a class="nav-link {% if menu.active %}active{% endif %}" href="{{ menu.href }}">{{ menu.title }}</a>
          </li>
          {% endif %}
          {% endfor %}
          {% if request.user.is_staff %}
          {% if not dt_content_preview_mode %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'dt-content:menu-create' %}?next={{ request.path }}">
              <i class="fas fa-cog"></i> Add Menu
            </a>
          </li>
          {% endif %}
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
</nav>

dt_content/templates/dt_content/example/site/page.html
{% extends 'dt_content/example/site/base.html' %}
{% load static %}
{% load dt_content %}

{% block head %}
<title>django-template</title>
<link rel="stylesheet" href="{% static 'dt_content/css/example/styles.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/navbar.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/header.css' %}">
<link rel="stylesheet" href="{% static 'dt_content/css/example/footer.css' %}">
{% endblock head%}
{% block body %}

{% include 'dt_content/example/site/navbar.html' %}

<!-- HEADER -->
<div class="header">
  <div class="header-background" style="background-image: url('{% static 'dt_content/img/example/background.jpg' %}')">
  </div>
  <div class="header-tint"></div>
  <div class="header-content">
    <div class="container header-container">
      {% if nav_menu.parent %} {# Child #}
      <div class="header-title d-flex flex-row">
        <a href="{{ nav_menu.parent.href }}" class="mr-3">{{ nav_menu.parent.title }}</a>
        <i class="fas fa-chevron-right mr-3"></i>
        <a href="{{ nav_menu.href }}" class="mr-3">{{ nav_menu.title }}</a>
      </div>
      {% else %} {# Parent #}
      <div class="header-title">
        <a href="{{ nav_menu.href }}" class="mr-3">{{ nav_menu.title }}</a>
      </div>
      {% endif %}
    </div>
  </div>
</div>

<!-- SUBMENU LIST -->
{% if nav_menu.children  %}
<div class="py-4 border-bottom">
  <div class="container">
    <!--<h2>{{ nav_menu.title }}</h2>-->
    <h2>Submenus</h2>
    {% for child in nav_menu.children %}
    <a href="{{ child.href }}" class="submenu-link">
      <i class="fas fa-chevron-circle-right"> </i>
      {{ child.title }}
    </a>
    {% endfor %}
  </div>
</div>
{% endif %}

{% if request.user.is_staff %}
{# Show these options even in preview mode #}
<div class="py-4 border-bottom">
  <div class="container">
    <h3>Admin Options</h3>
    {% if not nav_menu.parent %}
    <a href="{% url 'dt-content:submenu-create' %}?parent={{ nav_menu.id }}" class="submenu-link">
      <i class="fas fa-cog"> </i>
      Add Submenu
    </a>
    <a href="{% url 'dt-content:menu-update' nav_menu.id %}" class="submenu-link">
      <i class="fas fa-cog"> </i>
      Manage Menu
    </a>

    {% else %}
    <a href="{% url 'dt-content:submenu-update' nav_menu.id %}" class="submenu-link">
      <i class="fas fa-cog"> </i>
      Manage Submenu
    </a>
    {% endif %}

    {% if dt_content_preview_mode %}
    <a href="{% url 'dt-content:toggle-preview-mode' %}?mode=false&next={{ request.path }}" class="submenu-link">
      <i class="fas fa-eye"> </i>
      Exit Preview Mode
    </a>
    {% else %}
    <a href="{% url 'dt-content:toggle-preview-mode' %}?mode=true&next={{ request.path }}" class="submenu-link">
      <i class="fas fa-eye"> </i>
      View in Preview Mode
    </a>
    {% endif %}
  </div>
</div>
{% endif %}

<!-- CONTENT -->
<div class="content">
  {% include content_section.template_name %}
</div>

{% include 'dt_content/example/site/footer.html' %}

{% endblock body %}

{% block body_script %}
{% endblock body_script %}