app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("accounts/", include("allauth.urls")),
    path("dt-content/", include("dt_content.urls")),
    path("summernote/", include("django_summernote.urls")),
    # path('', include('social_django.urls', namespace='social')),  # enable for social login
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns.extend(static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT))
    urlpatterns.extend([path("__debug__/", include(debug_toolbar.urls))])

core/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import *

app_name = "core"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("work", WorkView.as_view(), name="work"),
    path("blog", BlogView.as_view(), name="blog"),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.apps import apps
from django.urls import reverse_lazy
from django.views.generic import TemplateView


class IndexView(TemplateView):
    template_name = "core/index.html"


class WorkView(TemplateView):
    template_name = "core/work.html"


class BlogView(TemplateView):
    template_name = "core/blog.html"

dt_content/views/core.py
import logging
from typing import Tuple

from django.http import Http404
from django.shortcuts import get_object_or_404
from django.views.generic.base import ContextMixin, TemplateView

from ..menu import get_nav_menu_list
from ..mixins import PreviewModeMixin
from ..models import *


class PageContextMixin(PreviewModeMixin, ContextMixin):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

    menu_base_url = "/"
    menu_path_kwarg = "menu_path"

    def get_menu_base_url(self):
        return str(self.menu_base_url)  # may be lazy

    def get_current_menu(self, request):
        menu_path = self.kwargs.get(self.menu_path_kwarg)
        if not menu_path:
            return None

        slugs = menu_path.split("/")

        if len(slugs) not in [1, 2]:
            logging.warning("Invalid menu_path {}".format(menu_path))

        parent_slug = slugs[0]
        parent = get_object_or_404(Menu, url_slug=parent_slug, parent=None)

        if len(slugs) == 2:
            child_slug = slugs[1]
            child = get_object_or_404(Menu, url_slug=child_slug, parent=parent)
            return child

        return parent

    def get_nav_menu_list(self):
        return get_nav_menu_list(
            self.get_menu_base_url(), self.request.path, self.get_preview_mode()
        )

    def get_page_context_data(self, **kwargs):
        page_context = dict()

        current_menu = self.get_current_menu(self.request)
        nav_menu_list = self.get_nav_menu_list()

        nav_menu = None
        if current_menu:
            if current_menu.parent:
                parent_menu = current_menu.parent
                child_menu = current_menu
            else:
                parent_menu = current_menu
                child_menu = None

            # Search parent
            for menu in nav_menu_list:
                if menu["id"] == parent_menu.id:
                    nav_menu = menu
                    break
            else:
                logging.warning("Could not find current parent menu in menu_list")

            # Search child if exists
            if child_menu:
                for menu in nav_menu["children"]:
                    if menu["id"] == child_menu.id:
                        nav_menu = menu
                        break
                else:
                    logging.warning("Could not find current child menu in menu_list")
            page_context["content_section"] = current_menu.get_content_section()
            page_context["nav_menu"] = nav_menu

        page_context["nav_menu_list"] = nav_menu_list
        page_context["dt_content_preview_mode"] = self.get_preview_mode()

        return page_context

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(self.get_page_context_data())
        return context


PageMixin = PageContextMixin  # deprecated


class PageView(PageContextMixin, TemplateView):
    """
    Examle usage:

    URL path: /menus/<parent_menu_slug>/<child_menu_slug?>
    URL pattern: /menus/<path:menu_path>
    `menu_base_url`: "/menus"
    `menu_path_kwarg`: "menu_path"

    ## Optimization Notes
    - Need to combine `get_current_menu` and `get_menu_list` for optimal performance.
      These methods are called for **every** page load.
    """

core/templates/core/blog.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load dt_content %}
{% load blurb %}
{% load image_blurb %}

{% block head %}
  <title>Django Template</title>
  <link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/blog.css' %}">
{% endblock head %}

{% block body %}

  {% include 'core/intro_header.html' with blog_active=True %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9">
        <div class="blog">
          <div class="title">제가 <span class="accent">지금까지 써온 글</span>입니다. 앞으로 계속 더 추가될 예정입니다 🦄</div>

          <div class="year">2017</div>
          <a class="post-card" href="https://medium.com/@itsnamgyu/python-기초기초오-for문-1-47576187e562" target="_blank">
            <div class="d-flex">
              <div class="icon">
                <i class="fab fa-medium"></i>
              </div>
              <div>
                <div class="header">
                  Python 기초기초오
                  <i class="fas fa-chevron-right chevron"></i>
                </div>
                <div class="description">
                  Python에서 for문 제대로 이해하기. 컴퓨팅사고력 학부 멘토 활동 중 학생들의 이해를 돕고자 간단하게 작성했습니다.
                </div>
              </div>
            </div>
          </a>

          <div class="year">2018</div>
          <a class="post-card" href="https://keraskorea.github.io/posts/2018-10-24-little_data_powerful_model/"
             target="_blank">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-link"></i>
              </div>
              <div>
                <div class="header">
                  작은 데이터셋으로 강력한 이미지 분류 모델 설계하기
                  <i class="fas fa-chevron-right chevron"></i>
                </div>
                <div class="description">
                  Keras 공식 튜토리얼 중 Francois Chollet의 "Building powerful image classification models using very
                  little data" 번역글. 2017년 Contributhon 프로젝트에서 진행한 번역입니다.
                </div>
              </div>
            </div>
          </a>

          <div class="year">2019</div>
          <a class="post-card" href="https://tutorials.pytorch.kr/recipes/recipes/loading_data_recipe.html"
             target="_blank">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-link"></i>
              </div>
              <div>
                <div class="header">
                  PyTorch에서 데이터 불러오기
                  <i class="fas fa-chevron-right chevron"></i>
                </div>
                <div class="description">
                  PyTorch 공식 튜토리얼 레시피 "Loading Data in PyTorch" 번역글.
                  2018년 Contributhon 프로젝트에서 진행한 번역입니다.
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>


{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/index.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load dt_content %}
{% load blurb %}
{% load image_blurb %}

{% block head %}
  <title>namgyu</title>
  <link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
{% endblock head %}

{% block body %}

  {% include 'core/intro_header.html' with home_active=True %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9">
        <div class="introduction">
          <div class="header">
            <span class="accent">I'm assuming...</span> <br>
            you want to know <br class="d-inline d-md-none">
            who I am 🌝
          </div>
          <div class="content animate__animated animate__fadeInUp">
            I'm a PhD student at KAIST working on large language models (LLMs) in NLP.
            I'm interested in making LLMs ready for the real world.
            I also learn 🎾.
          </div>
        </div>
      </div>

      <div class="col-12 col-md-9">
        <div class="shortcuts">
{#          <a href="{% url 'core:work' %}" class="btn link link-1 animate__animated animate__fadeInUp">#}
{#            <i class="fas fa-check-square mr-2"></i>지금까지 한 일<i class="fas fa-caret-right"></i>#}
{#          </a>#}
{#          <br>#}
{#          <a href="{% url 'core:blog' %}" class="btn link link-2 animate__animated animate__fadeInUp">#}
{#            <i class="fas fa-feather mr-2"></i>지금까지 쓴 글<i class="fas fa-caret-right"></i>#}
{#          </a>#}
{#          <br>#}
          <a href="https://twitter.com/itsnamgyu" target="_blank" class="btn link link-0 animate__animated animate__fadeInUp">
            <i class="fab fa-twitter mr-2"></i>Twitter<i class="fas fa-caret-right"></i>
          </a>
{#          <br>#}
          <a href="https://scholar.google.com/citations?user=4vOf7N8AAAAJ" target="_blank" class="btn link link-1 animate__animated animate__fadeInUp">
            <i class="fas fa-graduation-cap mr-2"></i>Google Scholar<i class="fas fa-caret-right"></i>
          </a>
{#          <br>#}
          <a href="https://github.com/itsnamgyu" target="_blank" class="btn link link-2 animate__animated animate__fadeInUp">
            <i class="fab fa-github mr-2"></i>GitHub<i class="fas fa-caret-right"></i>
          </a>
{#          <br>#}
          <a href="https://www.linkedin.com/in/itsnamgyu/" target="_blank" class="btn link link-3 animate__animated animate__fadeInUp">
            <i class="fab fa-linkedin mr-2"></i>LinkedIn<i class="fas fa-caret-right"></i>
          </a>
{#          <br>#}
          <a href="http://cv.namgyu.com" target="_blank" class="btn link link-4 animate__animated animate__fadeInUp">
            <i class="fas fa-scroll mr-2"></i>CV<i class="fas fa-caret-right"></i>
          </a>
        </div>
      </div>
    </div>
  </div>

{% endblock body %}
{% block body_script %}
{% endblock body_script %}

core/templates/core/intro_header.html
{% load static %}

<div class="intro-header">
  <div class="container">
    <div class="d-flex align-items-center">
      <div>
        <div class="header">namgyu ho</div>
        <div class="d-flex">
{#          <a href="{% url 'core:index' %}" class="btn tab {% if home_active %}active{% endif %}">Home</a>#}
{#          <a href="{% url 'core:work' %}" class="btn tab {% if work_active %}active{% endif %}">Work</a>#}
{#          <a href="{% url 'core:blog' %}" class="btn tab {% if blog_active %}active{% endif %}">Blog</a>#}
          {#              <a href="https://www.linkedin.com/in/itsnamgyu/" target="_blank" class="btn tab">LinkedIn</a>#}
          {#              <a href="https://www.github.com/itsnamgyu/" target="_blank" class="btn tab">GitHub</a>#}
        </div>
      </div>

      <a href="{% url 'core:index' %}" class="d-block ml-auto">
        <img class="profile-image" src="{% static 'core/img/profile.jpg' %}">
      </a>
    </div>
  </div>
</div>

core/templates/core/work.html
{% extends 'base/base.html' %}
{% load bootstrap4 %}
{% load static %}
{% load dt_content %}
{% load blurb %}
{% load image_blurb %}

{% block head %}
  <title>Django Template</title>
  <link rel="stylesheet" href="{% static 'dt_content/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'core/css/work.css' %}">
{% endblock head %}

{% block body %}

  {% include 'core/intro_header.html' with work_active=True %}

  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-9">
        <div class="work">
          <div class="title">제가 <span class="accent">지금까지 한 일</span>입니다 👨‍💻</div>

          <div class="work-card">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-flask"></i>
              </div>
              <div>
                <div class="header">
                  KAIST OSI 랩 인턴 [ 2021년 1월 - ]
                </div>
                <div class="description">
                  윤세영 교수님의 지도를 받고 person re-identification 연구를 진행하며 새로운 transductive loss,
                  hard-mining scheme 등을 고민중입니다.
                  <a href="https://www.notion.so/itsnamgyu/OSI-Research-a63335ec699946a4a379e720e45e81d4"
                     target="_blank">
                    연구 내용</a> 은 현재 Notion을 통해 공개하고 있습니다. Meta learning, optimization theory 관련 공동 연구도 함께
                  진행중입니다.
                </div>
              </div>
            </div>
          </div>

          <div class="work-card">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-flask"></i>
              </div>
              <div>
                <div class="header">
                  Person-in-the-Loop ReID 연구 [ 2020년 9월 - 2020년 10월 ]
                </div>
                <div class="description">
                  Person-in-the-loop을 이용한 re-ranking을 person re-identification 분야에 적용하기 위한
                  framework를 제시하고 hierarchical clustering에 기반한 새로운 기법을 제시하여 성능을 평가했습니다.
                  <a class="link" target="_blank" href="https://openreview.net/forum?id=C0lqfnLlTET">
                    NIPS 2020 HAMLETS 투고본 (4/4/5)
                    <i class="fas fa-chevron-right"></i>
                  </a>
                  <a class="link" target="_blank" href="https://www.google.com/search?q=Police-In-The-Loop+Person+Re-identification+openreview">
                    Alt: "Police-In-The-Loop Person Re-identification" @OpenReview
                    <i class="fas fa-chevron-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>

          <div class="work-card">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-building"></i>
              </div>
              <div>
                <div class="header">
                  ZionTech SWE 인턴 [ 2019년 4월 - 2019년 12월 ]
                </div>
                <div class="description">
                  캘리포니아 B2B 스타트업에서 Wavity SaaS 플랫폼 프론트엔드 담당. 후반부에는 프론트엔드 Angular 이전 프로젝트
                  팀을 리드하여 현재 서비스에 사용되는 코드베이스를 구축했습니다.
                  <a class="link" target="_blank" href="https://wavity.com">
                    www.wavity.com
                    <i class="fas fa-chevron-right"></i>
                  </a>
                </div>
              </div>
            </div>
          </div>

          <div class="work-card">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-flask"></i>
              </div>
              <div>
                <div class="header">
                  서울삼성병원 학부 연구생 [ 2018년 1월 - 2021년 3월 ]
                </div>
                <div class="description">
                  김윤철 교수님의 지도를 받고 심장 영상 분류에 딥러닝을 적용하는 연구를 진행했습니다. Cardiac short-axis MRI 사진의
                  slice-range 분류에 transfer learning을 적용하여 backbone 네트워크 및 fine-tuning 깊이에 따른 효과를 실험적으로
                  보였습니다.
                  <a class="link" target="_blank" href="https://index.mirasmart.com/ISMRM2019/PDFfiles/2133.html">
                    2019 ISMRM 학회 논문
                    <i class="fas fa-chevron-right"></i>
                  </a>
                  <a class="link" target="_blank" href="https://www.nature.com/articles/s41598-021-81525-9">
                    2021 Scientific Reports 학술지 논문
                    <i class="fas fa-chevron-right"></i>
                  </a>
                  <ul>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <div class="work-card">
            <div class="d-flex">
              <div class="icon">
                <i class="fas fa-graduation-cap"></i>
              </div>
              <div>
                <div class="header">
                  서강대학교 재학중 [ 2016년 3월 - ]
                </div>
                <div class="description">
                  컴퓨터공학 전공 (GPA 3.86/4.3). 학부 과정 중 집합론, 선형대수 과목을 가장 관심있게 공부했습니다. 학업 외에는 2017년 Release
                  과동아리 회장을 맡으며 Naver, Microsoft의 지원을 받아 세미나와 해커톤 등 각종 학술 활동을 운영했습니다.
                </div>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>


{% endblock body %}
{% block body_script %}
{% endblock body_script %}